### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by technically-speaking** [precurse/flacthis#6]
Error thrown when trying to encode audio. Running this

```
import flacthis

ft = flacthis.main(['--input_codec', 'flac', '--output_codec', 'mp3', source, output])
```
Throws this

```
ERROR:audio_converter:Could not encode
Traceback (most recent call last):
  File "C:\Users\technically-speaking\Python\flacthis\flacthis.py", line 325, in convert_to_lossy
    p1 = subprocess.Popen(src_args, stdout=subprocess.PIPE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Encoder exe files are in in the /flacthis directory and test detects them.

**Comment by precurse** [comment]
Hey! I haven't used this on Windows for a while, but let me see if I can reproduce the issue on my side.

**Comment by technically-speaking** [comment]
Thanks! I did a bit of digging on my own, adding shell=True to lines 325 & 326 in flacthis.py 

```
p1 = subprocess.Popen(src_args, stdout=subprocess.PIPE, shell=True)
p2 = subprocess.Popen(dest_args, stdin=p1.stdout, shell=True)
```
Seemed to resolve that error but returned in a different error in the file copy step on line 333
```
  File "C:\ProgramData\anaconda3\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified:
```

**Comment by precurse** [comment]
Oh interesting. Are you able to re-run with the ``--debug`` flag? That might help a bit

**Comment by technically-speaking** [comment]
Ran with the --debug flag, I'm not really sure what to make of this. Excerpt below of the part that throws an error.

```
DEBUG:audio_converter:translate got: C:\Users\technically-speaking\Music\Test\(1976) Boston\03 Foreplay  Long Time.flac
DEBUG:audio_converter:Encode output: None
DEBUG:audio_converter:INPUT command: C:\Users\technically-speaking\Python\flacthis\flac.exe -s -c -d "C:\Users\technically-speaking\Music\Test\(1976) Boston\04 Rock & Roll Band.flac" 
DEBUG:audio_converter:Dest_dir: C:\Users\technically-speaking\Music\TestN\(1976) Boston
DEBUG:audio_converter:OUTPUT command: C:\Users\technically-speaking\Python\flacthis\lame.exe - "C:\Users\technically-speaking\Music\TestN\(1976) Boston\04 Rock & Roll Band.tmp.mp3" --silent -V 0
DEBUG:audio_converter:\03 Foreplay  Long Time.flac
ERROR:audio_converter:Could not encode
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\technically-speaking\\Music\\TestN\\(1976) Boston\\08 Let Me Take You Home Tonight.tmp.mp3' -> 'C:\\Users\\technically-speaking\\Music\\TestN\\(1976) Boston\\08 Let Me Take You Home Tonight.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\technically-speaking\Python\flacthis\flacthis.py", line 333, in convert_to_lossy
    shutil.move(lossy_file_tmp, lossy_file)
  File "C:\ProgramData\anaconda3\Lib\shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "C:\ProgramData\anaconda3\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\ProgramData\anaconda3\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
```

**Comment by precurse** [comment]
It looks like it's trying to rename
```
 'C:\\Users\\technically-speaking\\Music\\TestN\\(1976) Boston\\08 Let Me Take You Home Tonight.tmp.mp3'
```
to
```
'C:\\Users\\technically-speaking\\Music\\TestN\\(1976) Boston\\08 Let Me Take You Home Tonight.mp3'
```

But it can't find the `.tmp.mp3` file. I wonder if there's an issue with the encoder failing prematurely, resulting in the file not being created.

I'm just in the process of seeing if I can reproduce the issue on a WSL system to test.

**Comment by technically-speaking** [comment]
That was my thought, that the error on rename was a red herring of sorts, the real issue being that its not encoding the file to start with.

**Comment by precurse** [comment]
Yeah that's what I'm thinking as well. Just to double check -- are you running this on native Windows or through WSL/WSL2?

**Comment by technically-speaking** [comment]
Sorry about the delay, I had a catastrophic system failure and had to reinstall OS and everything else.

I'm running native windows, and I'm using Anaconda + JupyterLab to run the commands in a notebook
